FROM alpine:3.21

RUN apk add --no-cache ca-certificates sqlite-libs

WORKDIR /app
COPY contactshq .
COPY configs ./configs
COPY migrations ./migrations

RUN mkdir -p /app/backups

EXPOSE 8080

CMD ["./contactshq"]
